// Package web provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package web

// CurrentNum defines model for CurrentNum.
type CurrentNum struct {
	// Num 現在の値
	Num int `json:"num"`
}

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// --以下クライアント--
// テンプレートを空にするためにここにはコメントのみ記載
// 参考: https://github.com/deepmap/oapi-codegen/blob/v1.8.2/pkg/codegen/templates/client.tmpl
// --以下レスポンス--
// 参考: https://github.com/deepmap/oapi-codegen/blob/v1.8.2/pkg/codegen/templates/client-with-responses.tmpl

type GetNumResponse struct {
	JSON200 struct {
		Result CurrentNum `json:"result"`
	}
	JSON500 Error
}
