version: "3.8"

services:
  app:
    image: app
    container_name: app
    build: .
    ports:
      - "8080:1323"
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "redis-volume:/data"

volumes:
  redis-volume:
