name: Go package

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: TEST_REDIS_HOST="redis" TEST_REDIS_PORT="6379" go test -v ./...
